### ISSUE TITLE
cpplibs/cmake-3.24.2/bin/cmake: No such file or directory

### ISSUE THREAD

**Issue by KlatbahII** [ignfab/building-roof-pipeline#2] opened 2022-12-15 08:56 UTC
Hello,

i tried to run your project on Ubuntu 20.04, but i got an issue when i run `build_cgal_component.sh`.  
The file cpplibs/cmake-3.24.2/bin/cmake doesn't exist.

```
build_cgal_components.sh: line 14: ../cpplibs/cmake-3.24.2/bin/cmake: No such file or directory
build_cgal_components.sh: line 15: ../cpplibs/cmake-3.24.2/bin/cmake: No such file or directory
```

I hope you can tell me what to do, because your pipeline and project seems really interesting.
Thanks

**Comment by esgn** [comment] 2023-01-17 14:27
Sorry for the delay. Your issue was lost in my mails at the end of last year. Will have a look into it soon.

**Comment by indyteo** [comment] 2023-01-17 17:50
Hello,
Thank you for your interest in this project!

I made a fresh install following the instruction from the README and went into the same error. This is caused by the fact that the tools & CPP libs are not installed: When running the `bash dl_and_build_cpplibs.sh -dc` script, I didn't noticed the first time there was a download issue (MPFR lib link is broken). And guess what? It's not the only one :cry:

As a temporary fix, I pushed a patched version of the script on the branch [`patch-broken-download-links`](https://github.com/ignfab/building-roof-pipeline/tree/patch-broken-download-links) (the MPFR version is also modified to `4.1`). Please check it out and start from step 2 here https://github.com/ignfab/building-roof-pipeline/tree/patch-broken-download-links#build-cgal-components-executables

Let me know if you encounter further issue with this project, I'd be happy to try my best to solve them! By the way, may I ask you what kind of work are you doing with this project? Always nice to see people that are interested by our work :blush:

**Comment by esgn** [comment] 2023-01-25 11:43
Hi @KlatbahII 
Main branch has been updated and fixed. Let us know if you still have trouble with it.

**Comment by esgn** [comment] 2023-02-09 09:54
Closing issue. Will reopen if needed.

**Closed as completed by esgn** 2023-02-09 09:54 UTC
